### PR TITLE
First batch of template items

### PR DESCRIPTION
**Pull request by damonmensch**

### CODE REVIEW

**Comment by Oddface** [comment]
Nice work!

**Comment by Oddface** [comment]
May I request an invitation for @damonmensch to join the contributor team?
@John-Smith-Modded/core

**Comment by goldbattle** [comment]
Sounds good to me, thanks for the outstanding work @damonmensch!

**Comment by damonmensch** [comment]
Thanks, just glad to be able to help keep pack alive

**Pull request merged**
